language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=7.8.3
    - GHCVER=head
    
global:
  - CABALVER=1.18
  - SKIP_HADDOCK=1
  
matrix:
  allow_failures:
    - env: GHCVER=head

script:
  - cabal install --only-dependencies && cabal configure && cabal build

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update

install:
  - cabal install --force-reinstalls

notifications:
  email:
      - twinside@gmail.com

